import os
import uuid
import hmac
import hashlib
import time
from fastapi import UploadFile, HTTPException, status
from sqlalchemy.orm import Session
from app.models.task import Task
from app.config import settings

# Where uploaded files are stored
UPLOAD_DIR = "uploads"

# How long presigned links are valid (in seconds)
LINK_EXPIRY_SECONDS = 3600  # 1 hour

def save_file(task_id: int, file: UploadFile, db: Session) -> dict:
    """
    Save an uploaded file to disk and store the path in the database.
    Returns file info including the filename and path.
    """
    # Make sure the task exists
    task = db.query(Task).filter(Task.id == task_id).first()
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task with id {task_id} not found"
        )

    # Generate a unique filename to avoid conflicts
    # e.g. "abc123-report.pdf" instead of "report.pdf"
    file_extension = os.path.splitext(file.filename)[1]
    unique_filename = f"{uuid.uuid4()}{file_extension}"
    file_path = os.path.join(UPLOAD_DIR, unique_filename)

    # Save the file to disk
    with open(file_path, "wb") as buffer:
        content = file.file.read()
        buffer.write(content)

    # Save the file path in the database
    task.file_path = file_path
    db.commit()
    db.refresh(task)

    return {
        "filename": unique_filename,
        "original_filename": file.filename,
        "file_path": file_path,
        "task_id": task_id
    }

def generate_presigned_link(task_id: int, db: Session) -> dict:
    """
    Generate a temporary signed URL for downloading a task's file.
    The link expires after LINK_EXPIRY_SECONDS.
    """
    # Make sure the task exists and has a file
    task = db.query(Task).filter(Task.id == task_id).first()
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task with id {task_id} not found"
        )
    if not task.file_path:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task {task_id} has no file attached"
        )

    # Generate expiry timestamp
    expires_at = int(time.time()) + LINK_EXPIRY_SECONDS

    # Create a signature using HMAC
    # This proves the link was generated by our server
    message = f"{task_id}:{task.file_path}:{expires_at}"
    signature = hmac.new(
        settings.secret_key.encode(),
        message.encode(),
        hashlib.sha256
    ).hexdigest()

    # Build the download URL
    download_url = (
        f"/tasks/{task_id}/download"
        f"?expires={expires_at}"
        f"&signature={signature}"
    )

    return {
        "download_url": download_url,
        "expires_in_seconds": LINK_EXPIRY_SECONDS,
        "filename": os.path.basename(task.file_path)
    }

def verify_and_get_file(task_id: int, expires: int, signature: str, db: Session) -> str:
    """
    Verify a presigned link and return the file path if valid.
    """
    # Check if link has expired
    if int(time.time()) > expires:
        raise HTTPException(
            status_code=status.HTTP_410_GONE,
            detail="Download link has expired"
        )

    # Get the task
    task = db.query(Task).filter(Task.id == task_id).first()
    if not task or not task.file_path:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="File not found"
        )

    # Verify the signature
    message = f"{task_id}:{task.file_path}:{expires}"
    expected_signature = hmac.new(
        settings.secret_key.encode(),
        message.encode(),
        hashlib.sha256
    ).hexdigest()

    if not hmac.compare_digest(signature, expected_signature):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid or tampered download link"
        )

    return task.file_path